### ISSUE TITLE
Dockerize hierarchical model

### ISSUE THREAD

**Issue by tmills** [Machine-Learning-for-Medical-Language/cnlp_transformers#136]
@dogversioning 's docker scripts assume each rest script has a unique model. the hier_rest module is generic to hierarchical models and can take in a model location as an environment variable. I don't know that we need to fix anything but might need a different looking example in the Dockerfile.* scripts for that model type.

**Comment by dogversioning** [comment]
Probably the simplest way to do this is by creating an [argument that could be set at container build time](https://stackoverflow.com/a/34600106/5318482)? and that could be added to the example buildx command.

**Comment by tmills** [comment]
Just to follow up on this, when we implement a new rest script, and add it to setup.cfg, it is hard to test the Docker build before pushing because the Docker install cnlp_transformer release, which does not yet have the new shortcuts implemented. Any suggestions for a workaround @dogversioning ?
