### ISSUE TITLE
handle case with varying numbers of dataset arguments and task name arguments.

### ISSUE THREAD

**Issue by tmills** [Machine-Learning-for-Medical-Language/cnlp_transformers#138]
Right now if the user passes in N dataset arguments with 1 task argument the code will choke during training even if both datasets contain the task. it should consolidate datasets at least in this easiest case and we should come up with a plan for the general case.

**Comment by tmills** [comment]
I think the solution is just to have every data directory that's read in represent every task in its data structure, with the label values all being mapped to -100 if the dataset doesn't contain that label, so pytorch will not compute a loss for that task for those data points. then ClinicalNLPDataset can be modified to not contain a list of datasets, but to be a single dataset that just concatenates all the datasets from the passed-in data_dirs.

**Comment by tmills** [comment]
Happy to hear any feedback if @angus-lherrou or @etgld have any thoughts.

**Comment by etgld** [comment]
This sounds good to me although I'm not super familiar with the use case

**Comment by angus-lherrou** [comment]
You'd probably want to add a check for each task that occurs in multiple datasets that e.g. the label space is the same or at least mostly overlapping and the output modes are the same, in case there happen to be separate tasks in the different datasets with coinciding names.

**Comment by tmills** [comment]
this will be in 0.7.0
