### ISSUE TITLE
Getting train, eval, dev, working so long as file columns fully overlap with task names

### ISSUE THREAD

**Issue by etgld** [Machine-Learning-for-Medical-Language/cnlp_transformers#188]
This would take some space to fully explain and more to replicate but I had an issue, that when I tried to run prediction on a file that had a Conmod column, for a model that had been trained for Conmod, that the new file confused the huggingface eval_loop due to it containing a new column that I added.  Running it with `--no_cuda` in particular seemed to cause an issue with computing loss.

I can maybe look into this more next week, but I think so long as the arguments provided to task_name are in the relevant files (along with the text column) for training, evaluation, or prediction, I think the other columns need not overlap.

If this ends up being really tough to do though in a pinch I think I can get away with using `cut` in bash to do column reorg, but sometimes that requires padding by randomly filling new columns

**Comment by etgld** [comment]
On additional examination, this might be something I did incorrectly in dev-error-analysis.  If it's there will try to fix before final PR

**Comment by etgld** [comment]
Checked this a while ago but forgot to update, it's a separate issue, will look more into it given the time

**Comment by tmills** [comment]
if you rediscover this issue just create a new one, will close this one out for clarity.
