### ISSUE TITLE
Newer HF transformers version saves model weights as model.safetensors instead of pytorch_model.bin

### ISSUE THREAD

**Issue by guo0O0o** [Machine-Learning-for-Medical-Language/cnlp_transformers#198]
Following sequence tagging Chemprot example gives errors on newer versions of HF transformers (currently on 4.41.2). Apparently `model.save_pretrained('folder/') ` now saves model as `.safetensors` rather than `.bin`

**Comment by tmills** [comment]
![image (4)](https://github.com/user-attachments/assets/b913e765-59e3-4b34-835c-229275645c20)

**Comment by tmills** [comment]
hmmm... I went to replicate this now and I can't get it to fail.

**Comment by tmills** [comment]
From @guo0O0o : i think you can also just add the flag --save_safetensors False at the end of your script
