### ISSUE TITLE
Pytorch version requirements in setup.cfg

### ISSUE THREAD

**Issue by wonjininfo** [Machine-Learning-for-Medical-Language/cnlp_transformers#201]
Hi

I was installing CNLPT on a new machine with CUDA 12.4 and found that the following line prevents me from using the newer version of Torch, which supports CUDA 12.4. 

https://github.com/Machine-Learning-for-Medical-Language/cnlp_transformers/blob/67deadbbb1d266c9609c7a33abcfd22c651d9314/setup.cfg#L38

I am currently testing the latest version of Torch, which is 2.5.0. Should there be any compatibility issues, I will post them in this thread.

**Comment by tmills** [comment]
@ianbulovic 's PR #200 will address this
