### ISSUE TITLE
Load the weights from a trained model for evaluation

### ISSUE THREAD

**Issue by dongfang91** [Machine-Learning-for-Medical-Language/cnlp_transformers#21]

**Comment by tmills** [comment]
i've been able to get this workflow to work, but it is only partially checked in. in train_system.py, it uses the constructor, but in the inference code it uses .from_pretrained() (that's the part that isn't committed yet). Check the most recent commit for updates on how to use the model and train_system: https://github.com/Machine-Learning-for-Medical-Language/cnlp_transformers/commit/c90ee824a79df03cdb7939bdae73c8a95fbc86f5

**Comment by dongfang91** [comment]
Got it, I will check that part of the code.

**Comment by dongfang91** [comment]
Main changes from lines 271-355.

1) move model registration before loading configuration files.
2) If load fine-tuned cnlpt models for evaluation, using AutoConfig.from_pretrained (line 298- 301) and model = CnlpModelForClassification.from_pretrained (line 325-321)
3) add a few if-else statements to check whether the model is pre-trained or whether we use the model for fine-tuning or evaluation.
