### ISSUE TITLE
Update REST APIs to ensure they use CnlpModelForClassification correctly

### ISSUE THREAD

**Issue by angus-lherrou** [Machine-Learning-for-Medical-Language/cnlp_transformers#28]
Currently, the negation API script does not work, as `AutoConfig` does not recognize `"model_type": "cnlpt"` in the `tmills/clinical_tempeval` config.

If I'm understanding the issue correctly, I think this means we will want to either register the `CnlpConfig` class with `AutoConfig` or use the `CnlpConfig` class directly instead of `AutoConfig`.

Additionally, `tmills/event-thyme-colon` and `tmills/timex-thyme-colon` still refer to `CnlpRobertaForClassification` in their configs in the `"architectures"` field. I'm not sure what that field is used for, but I assume it should be updated when we release the new package version.

**Comment by tmills** [comment]
I have local updates of the THYME rest servers that I haven't pushed yet.

**Comment by angus-lherrou** [comment]
Ah, cool.

If we wanted, I think we could register `CnlpConfig` with `AutoConfig` as soon as the user imports the `cnlpt` package.
