### ISSUE TITLE
`cnlpt.data` scripts are not in the library itself

### ISSUE THREAD

**Issue by angus-lherrou** [Machine-Learning-for-Medical-Language/cnlp_transformers#45]
Because there is no `src/cnlpt/data/__init__.py`, there is no `cnlpt.data` module in the library, and `src/cnlpt/data` is not included in the package install.

We should decide to either:
1. include these scripts in the package so users of the library can use these utility scripts for the i2b2 Obesity and UCI Drug Review corpora, or
2. move them to a separate directory to make it clear that they are not part of the library itself and instead ad-hoc scripts for specific datasets, and if users want to use them they should clone the repo instead.

**Comment by angus-lherrou** [comment]
requesting comment from @shan23chen and @tmills

**Comment by tmills** [comment]
Good catch. I think we should include them, mainly because we use them for our examples to show how to use the library, so people will need the scripts to follow the examples.

**Comment by shan23chen** [comment]
Yes I agree with Tim

**Comment by tmills** [comment]
checked in __init__ in cnlpt.data
