### ISSUE TITLE
Baseline models don't get saved

### ISSUE THREAD

**Issue by angus-lherrou** [Machine-Learning-for-Medical-Language/cnlp_transformers#52]
In `train_system`, `trainer.save_model` only gets invoked if the model is a `HierarchicalModel` or `CnlpModelForClassification`. This prevents trained `CnnSentenceClassifier` and `LstmSentenceClassifier` models from being reloaded and used for prediction.

**Comment by tmills** [comment]
during training, we get this message at the point where the Trainer object would be trying to save:
```Trainer.model is not a `PreTrainedModel`, only saving its state dict.```
