### ISSUE TITLE
changed command line flag from --model_name_or_path to --encoder_name

### ISSUE THREAD

**Issue by yfeng24816** [Machine-Learning-for-Medical-Language/cnlp_transformers#66]
I ended up changing the flag from `--model_name_or_path` to `--encoder_name` to run without error.

https://github.com/Machine-Learning-for-Medical-Language/cnlp_transformers/blob/b25312265ab1d0259e3eed92f3c3e9f87d5c7229/README.md?plain=1#L52

**Comment by tmills** [comment]
Thanks, I've updated this in the README in v0.3.0.
