### ISSUE TITLE
Add way to dynamically add processors to cnlp_processors

### ISSUE THREAD

**Issue by angus-lherrou** [Machine-Learning-for-Medical-Language/cnlp_transformers#77]
Currently, adding a processor in order to use the cnlp_transformers library for new tasks requires the following steps:

1. Clone the repository and install it in editable mode
2. Write a class in `cnlp_processors.py` that inherits from the proper base class, defining `get_labels` and `get_one_score`
3. Add the class to the `cnlp_processors` dictionary, defining a task name as the key
4. Add the task name and output mode (`mtl`, `classification`, `tagging`, or `relex`) to the `cnlp_output_modes` dictionary
5. If the task isn't a classification task, edit `cnlp_compute_metrics` to define which metrics to calculate for the task

Steps 2-4 can currently be done dynamically, without editing any files, obviating step 1. Step 5 requires code be edited or the `cnlp_compute_metrics` function be manually replaced in the `cnlpt.cnlp_processors` module, which is not a user-friendly workflow.

This process could be simplified so that users never have to clone the repository unless they want to contribute to the project itself; specifically, steps 3-5 could be abstracted into a function so that direct modification of module state is not exposed to the user.

**Comment by angus-lherrou** [comment]
Ongoing work on #17 and #96 should address this.

**Comment by tmills** [comment]
this is addressed in v0.4.0
